version: '3.9'
services:
  pgwriter:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=dbwriter,dbreader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.ci/postgres:/docker-entrypoint-initdb.d
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redisdata:/data
volumes:
  pgdata:
  redisdata:


