version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./web.Dockerfile
    ports: 
      - 8080:8080
    volumes:
      - .:/app
    environment:
       - DATABASE_READER_HOST=localhost
       - DATABASE_READER_USER=postgres
       - DATABASE_READER_PASSWORD=postgres
       - DATABASE_READER_NAME=dbreader
       - DATABASE_READER_PORT=5432
       - DATABASE_WRITER_HOST=localhost
       - DATABASE_WRITER_USER=postgres
       - DATABASE_WRITER_PASSWORD=postgres
       - DATABASE_WRITER_NAME=dbwriter
       - DATABASE_WRITER_PORT=5432
       - REDIS_DSN=127.0.0.1:6379
    networks:
      - this
    depends_on:
      - pg
  worker:
    build:
      context: .
      dockerfile: ./worker.Dockerfile
    volumes:
    - .:/app
    networks:
      - this
    depends_on:
      - pg
  pg:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=dbwriter,dbreader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.ci/postgres:/docker-entrypoint-initdb.d
    networks:
      - this
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redisdata:/data
    networks:
      - this
volumes:
  pgdata:
  redisdata:
networks:
 this:
   driver: bridge


